spring.data.mongodb.uri=mongodb://localhost:27017/arduinoshpd
spring.data.mongodb.database=arduinoshpd
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=MongoDB
spring.data.mongodb.password=
